#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
V307 APP REFLECT GUARD

Purpose:
- Make the final app-facing data reflect the latest EOD scanner output.
- Reads stock_candidates_input.csv generated by CV306+ scanner.
- Reads existing stock_candidates.json, live_quotes.json, recommendation_meta.json when present.
- Writes stock_candidates.json with ALL rows from stock_candidates_input.csv.
- Updates app_data_bundle.json candidate payload/count if the bundle exists.

Why this exists:
- Some downstream legacy scripts can overwrite the scanner output with an older fixed candidate set.
- This guard restores the scanner universe at the end of the pipeline while preserving any matched live/recommendation fields by code.
"""

from __future__ import annotations

import csv
import json
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Tuple

KST = timezone(timedelta(hours=9))
ROOT = Path(__file__).resolve().parents[1] if Path(__file__).parent.name == "scripts" else Path.cwd()

INPUT_CSV = ROOT / "stock_candidates_input.csv"
STOCK_JSON = ROOT / "stock_candidates.json"
BUNDLE_JSON = ROOT / "app_data_bundle.json"
LIVE_QUOTES_JSON = ROOT / "live_quotes.json"
RECOMMENDATION_META_JSON = ROOT / "recommendation_meta.json"
OUT_SUMMARY = ROOT / "v307_app_reflect_summary.json"
OUT_TXT = ROOT / "v307_app_reflect_summary.txt"

VERSION = "V307_APP_REFLECT_GUARD"


def now_kst() -> str:
    return datetime.now(KST).strftime("%Y-%m-%d %H:%M:%S")


def norm_code(value: Any) -> str:
    s = str(value or "").strip()
    if not s or s == "-":
        return ""
    digits = "".join(ch for ch in s if ch.isdigit())
    if digits:
        return digits.zfill(6)[-6:]
    return s


def clean(value: Any, default: str = "-") -> str:
    if value is None:
        return default
    s = str(value).strip()
    return s if s else default


def to_int(value: Any, default: int = 0) -> int:
    try:
        s = str(value or "").replace(",", "").replace("%", "").strip()
        if not s or s == "-":
            return default
        return int(round(float(s)))
    except Exception:
        return default


def to_float(value: Any, default: float = 0.0) -> float:
    try:
        s = str(value or "").replace(",", "").replace("%", "").strip()
        if not s or s == "-":
            return default
        return float(s)
    except Exception:
        return default


def read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def read_csv(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"{path.name} not found")
    for enc in ["utf-8-sig", "utf-8", "cp949", "euc-kr"]:
        try:
            with path.open("r", encoding=enc, newline="") as f:
                return list(csv.DictReader(f))
        except UnicodeDecodeError:
            continue
    raise RuntimeError(f"failed to read {path.name}")


def extract_rows(data: Any) -> List[Dict[str, Any]]:
    if isinstance(data, list):
        return [x for x in data if isinstance(x, dict)]
    if isinstance(data, dict):
        for key in ["candidates", "items", "stocks", "data", "results"]:
            val = data.get(key)
            if isinstance(val, list):
                return [x for x in val if isinstance(x, dict)]
    return []


def by_code(rows: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    out: Dict[str, Dict[str, Any]] = {}
    for row in rows:
        code = norm_code(row.get("code") or row.get("종목코드") or row.get("symbol"))
        if code:
            out[code] = row
    return out


def build_live_map(data: Any) -> Dict[str, Dict[str, Any]]:
    rows = []
    if isinstance(data, dict) and isinstance(data.get("quotes"), list):
        rows = data["quotes"]
    elif isinstance(data, list):
        rows = data
    return by_code([x for x in rows if isinstance(x, dict)])


def grade_from_score(score: int) -> str:
    if score >= 90:
        return "S"
    if score >= 80:
        return "A"
    if score >= 70:
        return "B"
    if score >= 60:
        return "C"
    return "D"


def action_from_score(score: int, grade: str) -> str:
    if grade == "S" or score >= 88:
        return "우선검토"
    if grade == "A" or score >= 78:
        return "조건확인"
    if grade == "B" or score >= 68:
        return "관찰"
    return "보류"


def row_value(row: Dict[str, Any], keys: List[str], default: Any = "-") -> Any:
    for key in keys:
        val = row.get(key)
        if val not in [None, "", "-"]:
            return val
    return default


def build_item(src: Dict[str, Any], idx: int, existing: Dict[str, Any], live: Dict[str, Any]) -> Dict[str, Any]:
    code = norm_code(row_value(src, ["code", "종목코드", "symbol"], ""))
    name = clean(row_value(src, ["name", "종목명", "stockName"], existing.get("name", f"후보 {idx}")))

    score = to_int(row_value(src, ["score", "recommendationScore", "점수"], existing.get("score", 70)), 70)
    grade = clean(row_value(src, ["grade", "recommendationGrade", "등급"], existing.get("grade", "")), "")
    if not grade or grade == "-":
        grade = grade_from_score(score)

    action = clean(existing.get("recommendationAction"), "")
    if not action or action == "-":
        action = action_from_score(score, grade)

    # Start from scanner row to avoid legacy 24-item lock, then preserve useful existing enrichment.
    item: Dict[str, Any] = {
        "rank": idx,
        "name": name,
        "code": code or clean(existing.get("code")),
        "score": score,
        "grade": grade,
        "reason": clean(row_value(src, ["reason", "summary", "사유"], existing.get("reason", "종가 기준 자동선별 후보"))),
        "market": clean(row_value(src, ["market", "시장"], existing.get("market", "-"))),
        "sector": clean(row_value(src, ["sector", "industry", "업종", "섹터"], existing.get("sector", existing.get("industry", "-")))),
        "changeRate": clean(row_value(src, ["changeRate", "등락률"], existing.get("changeRate", "-"))),
        "entryPrice": clean(row_value(src, ["entryPrice", "진입가"], existing.get("entryPrice", "종가 기준 지지 확인"))),
        "stopLoss": clean(row_value(src, ["stopLoss", "손절가"], existing.get("stopLoss", "20일선 또는 전저점 이탈"))),
        "targetPrice": clean(row_value(src, ["targetPrice", "목표가"], existing.get("targetPrice", "분할 익절"))),
        "strategy": clean(row_value(src, ["strategy", "전략"], existing.get("strategy", "종가 기준 후보 / 다음 거래일 조건 확인"))),
        "weeklyCloud": clean(row_value(src, ["weeklyCloud", "주봉구름대"], existing.get("weeklyCloud", "주봉 추세 확인"))),
        "dailySignal": clean(row_value(src, ["dailySignal", "일봉신호"], existing.get("dailySignal", "종가 기준 확인"))),
        "rsi": clean(row_value(src, ["rsi", "RSI"], existing.get("rsi", "RSI 확인"))),
        "macd": clean(row_value(src, ["macd", "MACD"], existing.get("macd", "MACD 확인"))),
        "volumeSignal": clean(row_value(src, ["volumeSignal", "거래량신호"], existing.get("volumeSignal", "거래량 확인"))),
        "reportSignal": clean(row_value(src, ["reportSignal", "리포트신호"], existing.get("reportSignal", "리포트 확인"))),
        "newsSignal": clean(row_value(src, ["newsSignal", "뉴스신호"], existing.get("newsSignal", "뉴스 확인"))),
        "riskMemo": clean(row_value(src, ["riskMemo", "리스크"], existing.get("riskMemo", "종가 기준 후보: 다음 거래일 이격·거래량 확인"))),
    }

    preserve_keys = [
        "foreign5D", "foreign20D", "foreign60D",
        "pension5D", "pension20D", "pension60D",
        "trust5D", "trust20D", "trust60D",
        "finance5D", "finance20D", "finance60D",
        "supplyMemo", "supplyReflectionStatus",
        "recommendationVersion", "recommendationBreakdown", "recommendationReason", "hasRecommendationMeta",
        "currentPrice", "priceChangeRate", "weeklyCloudBreakout", "dailyCloudBreakout",
        "technicalScore", "flowScore", "issueScore", "flowDataStatus",
    ]
    for key in preserve_keys:
        if key in existing:
            item[key] = existing[key]
        elif key in src:
            item[key] = src[key]

    # Attach live quote, preferring current live data if present.
    live_price = live.get("price") or live.get("currentPrice") or live.get("livePrice") or existing.get("livePrice")
    if live_price not in [None, "", "-"]:
        item["livePrice"] = clean(live_price)
        item["currentPriceLive"] = clean(live_price)
        item["realTimePrice"] = clean(live_price)
        item["hasLiveQuote"] = True
        item["liveSource"] = clean(live.get("source"), existing.get("liveSource", "naver_finance"))
        item["liveUpdatedAt"] = clean(live.get("updatedAt"), existing.get("liveUpdatedAt", now_kst()))
    else:
        item["hasLiveQuote"] = bool(existing.get("hasLiveQuote", False))

    if live.get("volume") not in [None, "", "-"]:
        item["liveVolume"] = clean(live.get("volume"))
    elif existing.get("liveVolume"):
        item["liveVolume"] = existing.get("liveVolume")

    if live.get("changeRate") not in [None, "", "-"]:
        item["liveChangeRate"] = clean(live.get("changeRate"))
    elif existing.get("liveChangeRate"):
        item["liveChangeRate"] = existing.get("liveChangeRate")

    base_status = existing.get("dataStatus") if isinstance(existing.get("dataStatus"), dict) else {}
    item["dataStatus"] = {
        **base_status,
        "baseScore": to_int(base_status.get("baseScore"), score),
        "scannerScore": score,
        "scannerVersion": VERSION,
        "finalRecommendationScore": to_int(existing.get("recommendationScore"), score),
        "recommendationAction": action,
        "reflectedBy": VERSION,
        "reflectedAt": now_kst(),
    }

    item["recommendationAction"] = action
    item["recommendationGrade"] = clean(existing.get("recommendationGrade"), grade)
    item["recommendationScore"] = to_int(existing.get("recommendationScore"), score)
    item["recommendationMeta"] = existing.get("recommendationMeta") if isinstance(existing.get("recommendationMeta"), dict) else {
        "version": VERSION,
        "rank": idx,
        "score": item["recommendationScore"],
        "grade": item["recommendationGrade"],
        "action": action,
        "basis": ["eod_scanner", "market_universe", "close_based_strategy"],
        "updatedAt": f"{now_kst()} KST",
    }
    item["recommendationMeta"]["rank"] = idx
    item["recommendationMeta"]["appReflectVersion"] = VERSION

    return item


def top_candidates(rows: List[Dict[str, Any]], limit: int = 10) -> List[Dict[str, Any]]:
    out = []
    for row in rows[:limit]:
        out.append({
            "rank": row.get("rank", len(out) + 1),
            "name": row.get("name", "-"),
            "code": row.get("code", "-"),
            "score": row.get("recommendationScore", row.get("score", "-")),
            "grade": row.get("recommendationGrade", row.get("grade", "-")),
            "reason": row.get("recommendationReason", row.get("reason", "-")),
        })
    return out


def update_bundle(candidates: List[Dict[str, Any]]) -> bool:
    if not BUNDLE_JSON.exists():
        return False
    bundle = read_json(BUNDLE_JSON, {})
    if not isinstance(bundle, dict):
        return False
    bundle["version"] = "V307_APP_DATA_BUNDLE_REFLECTED"
    bundle["updatedAt"] = now_kst()
    bundle["candidateCount"] = len(candidates)
    bundle["topCandidates"] = top_candidates(candidates, 10)
    payload = bundle.get("payload")
    if not isinstance(payload, dict):
        payload = {}
    payload["candidates"] = candidates
    bundle["payload"] = payload
    warnings = bundle.get("warnings") if isinstance(bundle.get("warnings"), list) else []
    warnings = [w for w in warnings if "후보 수" not in str(w)]
    bundle["warnings"] = warnings
    if bundle.get("status") == "warning" and not warnings:
        bundle["status"] = "ok"
    bundle["appReflect"] = {
        "version": VERSION,
        "candidateCount": len(candidates),
        "updatedAt": now_kst(),
    }
    BUNDLE_JSON.write_text(json.dumps(bundle, ensure_ascii=False, indent=2), encoding="utf-8")
    return True


def main() -> None:
    input_rows = read_csv(INPUT_CSV)
    old_candidates = extract_rows(read_json(STOCK_JSON, []))
    old_map = by_code(old_candidates)
    live_map = build_live_map(read_json(LIVE_QUOTES_JSON, {}))

    output: List[Dict[str, Any]] = []
    seen = set()
    for row in input_rows:
        code = norm_code(row_value(row, ["code", "종목코드", "symbol"], ""))
        if not code or code in seen:
            continue
        seen.add(code)
        item = build_item(row, len(output) + 1, old_map.get(code, {}), live_map.get(code, {}))
        output.append(item)

    if not output:
        raise SystemExit("[FAIL] no candidates built from stock_candidates_input.csv")

    # Keep scanner order/rank. Do not sort by legacy recommendation score, because that can re-lock old 24 rows.
    STOCK_JSON.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    bundle_updated = update_bundle(output)

    summary = {
        "version": VERSION,
        "updatedAt": now_kst(),
        "inputCsvRows": len(input_rows),
        "previousCandidateCount": len(old_candidates),
        "finalCandidateCount": len(output),
        "bundleUpdated": bundle_updated,
        "first5": [{"rank": x.get("rank"), "name": x.get("name"), "code": x.get("code")} for x in output[:5]],
    }
    OUT_SUMMARY.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    OUT_TXT.write_text("\n".join([
        "V307 APP REFLECT GUARD",
        f"updatedAt: {summary['updatedAt']}",
        f"inputCsvRows: {summary['inputCsvRows']}",
        f"previousCandidateCount: {summary['previousCandidateCount']}",
        f"finalCandidateCount: {summary['finalCandidateCount']}",
        f"bundleUpdated: {summary['bundleUpdated']}",
    ]), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
